Closes #532 -- Problem with amounts in inventory
Brewtarget/brewtarget pull request #536
Opened 2021-03-31 21:09 UTC by mikfire

The code was working as designed, I just had a bad design. I had missed
this use-case, and so the original's inventory_id was copied along
with the rest.

The fix was to add a boolean to the new* calls in Database that allowed
us to specify if we wanted a new inventory row or not. Since this
allowed me to declutter some of the code, I think it is a reasonable
approach.

The only path I could find that needed this was from
BtTreeModel::copySelected, so that method got modified to request the
new inventory row. I had considered putting the code to add a new
inventory row here, which had the benefit of keeping the complexity
close to where it was used. But I didn't like the model having to open a
transaction, so I put into the Database methods.

My quick testing makes me think this is working better.

2021-04-06 07:51 UTC, mattiasmaahl commented
I was reading through the code and tried to build it on my Debian, and it failed due to a function/method not being defined.

Question: Where can I find the function/method newIngredient(...)?

2021-04-06 08:44 UTC, matty0ung commented
This is probably a merge issue.  It's now called newNamedEntity().  (Not all Ingredients were ingredients, if you see what I mean, so I changed the name of the class to NamedEntity as part of the XML work.  There's a comment in the code in model/NamedEntity.h that elaborates a bit more.)

2021-04-06 08:47 UTC, mattiasmaahl commented
Aha, ok. Now that you're saying it I do remember that discussion/PR. then it's an easy fix for Mik to do before merge. :smile:

2021-04-06 09:07 UTC, mattiasmaahl commented on src/database.cpp
> +         tmp = newIngredient(&allFermentables);
Should be: 
tmp = newNamedEntity(&allFermentables);

2021-04-06 09:08 UTC, mattiasmaahl requested changes
All the newInventory(...) need to be changed to newNamedEntity(...) before merge

2021-04-06 15:16 UTC, mikfire commented
Ugh. Missed that part. I'll update after work.

2021-04-08 05:20 UTC, mattiasmaahl approved these changes
Builds and runs.

2021-04-08 05:20 UTC, merged